name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v3.1.0)'
        required: true
        default: 'v3.1.0'

env:
  DOTNET_VERSION: '6.0.x'
  SOLUTION_PATH: 'AutoRip2MKV_3.sln'

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for changelog generation
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --configuration Release --verbosity normal
      
    - name: Publish application (Self-contained)
      run: |
        dotnet publish AutoRip2MKV/AutoRip2MKV.csproj `
          --configuration Release `
          --framework net6.0-windows `
          --output ./publish/AutoRip2MKV-SelfContained `
          --self-contained true `
          --runtime win-x64 `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true
          
    - name: Publish application (Framework-dependent)
      run: |
        dotnet publish AutoRip2MKV/AutoRip2MKV.csproj `
          --configuration Release `
          --framework net6.0-windows `
          --output ./publish/AutoRip2MKV-FrameworkDependent `
          --self-contained false `
          --runtime win-x64
          
    - name: Copy installer files
      run: |
        Copy-Item -Path "Installer/*" -Destination "./publish/Installer" -Recurse -Force
        
    - name: Create release packages
      run: |
        # Self-contained release
        Compress-Archive -Path ./publish/AutoRip2MKV-SelfContained/* -DestinationPath ./AutoRip2MKV-v3.1.0-SelfContained.zip
        
        # Framework-dependent release
        Compress-Archive -Path ./publish/AutoRip2MKV-FrameworkDependent/* -DestinationPath ./AutoRip2MKV-v3.1.0-FrameworkDependent.zip
        
        # Installer package
        Compress-Archive -Path ./publish/Installer/* -DestinationPath ./AutoRip2MKV-v3.1.0-Installer.zip
        
        # Combined release with all components
        Remove-Item -Recurse -Force "./combined-release" -ErrorAction SilentlyContinue
        New-Item -ItemType Directory -Path "./combined-release/Installer" -Force
        Copy-Item -Path "./publish/AutoRip2MKV-SelfContained/*" -Destination "./combined-release/" -Recurse
        Copy-Item -Path "./publish/Installer/*" -Destination "./combined-release/Installer/" -Recurse
        Copy-Item -Path "README.md" -Destination "./combined-release/"
        Compress-Archive -Path ./combined-release/* -DestinationPath ./AutoRip2MKV-v3.1.0-Complete.zip
        
    - name: Get release version
      id: get_version
      shell: pwsh
      run: |
        if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
          $version = "${{ github.event.inputs.version }}"
        } else {
          $version = $env:GITHUB_REF -replace 'refs/tags/', ''
        }
        echo "version=$version" >> $env:GITHUB_OUTPUT
        echo "version_name=AutoRip2MKV $version" >> $env:GITHUB_OUTPUT
        
    - name: Generate release notes
      id: release_notes
      shell: pwsh
      run: |
        # Get current version
        if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
          $currentVersion = "${{ github.event.inputs.version }}"
        } else {
          $currentVersion = $env:GITHUB_REF -replace 'refs/tags/', ''
        }
        
        # Get previous tag for changelog range (if any)
        $previousTag = git tag --sort=-version:refname | Where-Object { $_ -ne $currentVersion } | Select-Object -First 1
        
        # Generate commit log since last tag or from beginning
        if ($previousTag) {
          $commitRange = "$previousTag..HEAD"
          $changelogHeader = "## Changes since $previousTag"
        } else {
          $commitRange = "HEAD"
          $changelogHeader = "## All Changes in this Release"
        }
        
        # Get commit messages and format them
        $commits = git log $commitRange --pretty=format:"%h - %s" --no-merges
        $formattedCommits = ""
        if ($commits) {
          $commitLines = $commits -split "`n"
          foreach ($commit in $commitLines) {
            if ($commit.Trim()) {
              $formattedCommits += "- $commit`n"
            }
          }
        } else {
          $formattedCommits = "- Initial release`n"
        }
        
        # Get merge commits for major features
        $mergeCommits = git log $commitRange --pretty=format:"%h - %s" --merges
        $formattedMerges = ""
        if ($mergeCommits) {
          $mergeLines = $mergeCommits -split "`n"
          foreach ($merge in $mergeLines) {
            if ($merge.Trim() -and $merge -match "Merge pull request") {
              $formattedMerges += "- $merge`n"
            }
          }
        }
        
        $releaseNotes = @"
        # AutoRip2MKV $currentVersion Release
        
        ## What's New in $currentVersion
        - Enhanced CI/CD pipeline with automated builds and releases
        - Improved installer packaging and distribution
        - Updated to .NET 6 framework with modern C# features
        - Comprehensive test coverage and security scanning
        - Multiple release formats for different deployment scenarios
        
        ## Download Options
        
        ### Recommended Downloads
        - **AutoRip2MKV-$($currentVersion.TrimStart('v'))-Complete.zip** - Complete package with application and installer
        - **AutoRip2MKV-$($currentVersion.TrimStart('v'))-SelfContained.zip** - Standalone executable (no .NET required)
        
        ### Additional Downloads
        - **AutoRip2MKV-$($currentVersion.TrimStart('v'))-FrameworkDependent.zip** - Requires .NET 6 Runtime
        - **AutoRip2MKV-$($currentVersion.TrimStart('v'))-Installer.zip** - MSI installer package only
        
        ## System Requirements
        - Windows 10 or later (x64)
        - .NET 6 Runtime (for framework-dependent version)
        - MakeMKV installed and configured
        - HandBrake CLI (included in package)
        
        ## Installation
        1. Download the Complete package or Self-contained version
        2. Extract to your preferred location
        3. Run AutoRip2MKV.exe
        4. Alternatively, use the MSI installer from the Installer folder for system-wide installation
        
        $changelogHeader
        
        ### Commits
        $formattedCommits
        $(if ($formattedMerges) { "### Major Features (Pull Requests)`n$formattedMerges" })
        
        ## Technical Details
        - Built with .NET 6.0 targeting Windows
        - Automated CI/CD pipeline with GitHub Actions
        - Comprehensive test suite with code coverage
        - Security vulnerability scanning
        - Multiple deployment formats supported
        
        ---
        
        For technical support, bug reports, or feature requests, please visit the [GitHub repository](https://github.com/gmoyle/AutoRip2MKV_3).
        "@
        
        $releaseNotes | Out-File -FilePath release_notes.md -Encoding utf8
        echo "notes_file=release_notes.md" >> $env:GITHUB_OUTPUT
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: ${{ steps.get_version.outputs.version_name }}
        body_path: ${{ steps.release_notes.outputs.notes_file }}
        draft: false
        prerelease: false
        files: |
          ./AutoRip2MKV-v3.1.0-Complete.zip
          ./AutoRip2MKV-v3.1.0-SelfContained.zip
          ./AutoRip2MKV-v3.1.0-FrameworkDependent.zip
          ./AutoRip2MKV-v3.1.0-Installer.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts for debugging
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: |
          ./AutoRip2MKV-v3.1.0-*.zip
          ./publish/**
        retention-days: 7
